---
- hosts: db2
  remote_user: root
  vars_files:
    - files/vars.yaml

  tasks:
    - name: Install Package
      yum: name={{ pkname }}
      tags: install

    - name: Start Service
      service: name={{ pkname }} state=started enabled=yes
      tags: start

    - name: Copy Cm6
      copy: src={{ download_path }}/cm6.2.1-redhat7.tar.gz dest=/tmp mode=755
    
    - name: Mkdir Dre
      file: path=/var/www/html/cloudera-repos/cm6    state=directory 
      tags: Mkdir

    - name: Unzip Cm6
      shell: "tar zxvf /tmp/cm6.2.1-redhat7.tar.gz -C /var/www/html/cloudera-repos/cm6 --strip-components=1"
      tags: tar

    - name: Copy cm-repos
      template: src=cloudera-repo.repo.j2 dest=/etc/yum.repos.d/cloudera-repo.repo

    - name: Install Cm6
      shell: "yum install -y cloudera-manager-daemons cloudera-manager-agent cloudera-manager-server"

    - name: install mysql
      shell: "yum install -y mariadb-server"
      tags: installdb

    - name: copy my.cnf 
      template: src=my.cnf dest=/etc/my.cnf backup=true
      tags: installdb

    - name: start mysql
      service: name=mariadb state=restarted
      tags: installdb

    - name: create jdbc ad
      file: path=/usr/share/java/    state=directory
      tags: installdb

    - name: copy jdbc-jars to remote hosts
      copy:
        src: mysql-connector-java.jar
        dest: /usr/share/java/

    - name: init mysql
      script: scripts/mysql_cdh_init.sh creates=/tmp/cdh_mysql_init
      tags: installdb3

    - name: mkdir cdh-repo
      file: path=/opt/cloudera/parcel-repo    state=directory
      tags: installcdh

    - name: cp cdh.cloudera
      copy: src=~/Desktop/hadoop/CDH-6.2.1-1.cdh6.2.1.p0.1425774-el7.parcel dest=/opt/cloudera/parcel-repo/
      tags: installcdh

    - name: cp cdhhash
      copy: src=~/Desktop/hadoop/CDH-6.2.1-1.cdh6.2.1.p0.1425774-el7.parcel.sha dest=/opt/cloudera/parcel-repo/
      tags: installcdh

    - name: chown user
      shell: "chown -R cloudera-scm:cloudera-scm /opt/cloudera/parcel-repo/*"
      tags: installcdh

    - name: start server
      service: name=cloudera-scm-server state=started enabled=yes
      tags: installcdh2
    
