---
- hosts: hadoop
  remote_user: root

  tasks:
    - name: Import Elrepo PG key
      rpm_key: "key={{ item }} state=present"
      with_items:
        - "https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"

    - name: Install elrepo
      command: "rpm -Uvh --force {{ item.href }}  creates={{ item.creates }}"
      with_items:
        - href: "http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm"
          creates: "/etc/yum.repos.d/kernel.repo"

    - name: Install epel repo
      yum: name=kernel-lt state=present enablerepo=elrepo-kernel

    - name: Sed grub config
      shell: "sed -i s/GRUB_DEFAULT=saved/GRUB_DEFAULT=0/g /etc/default/grub"

    - name: Grub mkconfig
      shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"